//
// ErrorModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ErrorModel: Codable {

    public var message: String
    public var code: Int

    public init(message: String, code: Int) {
        self.message = message
        self.code = code
    }

}
