//
// Recipe.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Recipe: Codable, Hashable {

    public var title: String?
    public var href: String
    public var ingredients: String?
    public var thumbnail: String?

    public init(title: String? = nil, href: String, ingredients: String? = nil, thumbnail: String? = nil) {
        self.title = title
        self.href = href
        self.ingredients = ingredients
        self.thumbnail = thumbnail
    }

}
