//
// InlineResponse2002Results.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2002Results: Codable {

    public var displayName: String?
    public var listName: String?
    public var listNameEncoded: String?
    public var newestPublishedDate: String?
    public var oldestPublishedDate: String?
    public var updated: String?

    public init(displayName: String? = nil, listName: String? = nil, listNameEncoded: String? = nil, newestPublishedDate: String? = nil, oldestPublishedDate: String? = nil, updated: String? = nil) {
        self.displayName = displayName
        self.listName = listName
        self.listNameEncoded = listNameEncoded
        self.newestPublishedDate = newestPublishedDate
        self.oldestPublishedDate = oldestPublishedDate
        self.updated = updated
    }

    public enum CodingKeys: String, CodingKey { 
        case displayName = "display_name"
        case listName = "list_name"
        case listNameEncoded = "list_name_encoded"
        case newestPublishedDate = "newest_published_date"
        case oldestPublishedDate = "oldest_published_date"
        case updated
    }

}
