//
// InlineResponse200Results.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200Results: Codable {

    public var amazonProductUrl: String?
    public var asterisk: Int?
    public var bestsellersDate: String?
    public var bookDetails: [InlineResponse200BookDetails]?
    public var dagger: Int?
    public var displayName: String?
    public var isbns: [InlineResponse2001Isbns]?
    public var listName: String?
    public var publishedDate: String?
    public var rank: Int?
    public var rankLastWeek: Int?
    public var reviews: [InlineResponse2001Reviews]?
    public var weeksOnList: Int?

    public init(amazonProductUrl: String? = nil, asterisk: Int? = nil, bestsellersDate: String? = nil, bookDetails: [InlineResponse200BookDetails]? = nil, dagger: Int? = nil, displayName: String? = nil, isbns: [InlineResponse2001Isbns]? = nil, listName: String? = nil, publishedDate: String? = nil, rank: Int? = nil, rankLastWeek: Int? = nil, reviews: [InlineResponse2001Reviews]? = nil, weeksOnList: Int? = nil) {
        self.amazonProductUrl = amazonProductUrl
        self.asterisk = asterisk
        self.bestsellersDate = bestsellersDate
        self.bookDetails = bookDetails
        self.dagger = dagger
        self.displayName = displayName
        self.isbns = isbns
        self.listName = listName
        self.publishedDate = publishedDate
        self.rank = rank
        self.rankLastWeek = rankLastWeek
        self.reviews = reviews
        self.weeksOnList = weeksOnList
    }

    public enum CodingKeys: String, CodingKey { 
        case amazonProductUrl = "amazon_product_url"
        case asterisk
        case bestsellersDate = "bestsellers_date"
        case bookDetails = "book_details"
        case dagger
        case displayName = "display_name"
        case isbns
        case listName = "list_name"
        case publishedDate = "published_date"
        case rank
        case rankLastWeek = "rank_last_week"
        case reviews
        case weeksOnList = "weeks_on_list"
    }

}
