//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200: Codable {

    public var copyright: String?
    public var lastModified: String?
    public var numResults: Int?
    public var results: [InlineResponse200Results]?
    public var status: String?

    public init(copyright: String? = nil, lastModified: String? = nil, numResults: Int? = nil, results: [InlineResponse200Results]? = nil, status: String? = nil) {
        self.copyright = copyright
        self.lastModified = lastModified
        self.numResults = numResults
        self.results = results
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case copyright
        case lastModified = "last_modified"
        case numResults = "num_results"
        case results
        case status
    }

}
