//
// InlineResponse2005Results.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2005Results: Codable {

    public var bookAuthor: String?
    public var bookTitle: String?
    public var byline: String?
    public var isbn13: [String]?
    public var publicationDt: String?
    public var summary: String?
    public var url: String?

    public init(bookAuthor: String? = nil, bookTitle: String? = nil, byline: String? = nil, isbn13: [String]? = nil, publicationDt: String? = nil, summary: String? = nil, url: String? = nil) {
        self.bookAuthor = bookAuthor
        self.bookTitle = bookTitle
        self.byline = byline
        self.isbn13 = isbn13
        self.publicationDt = publicationDt
        self.summary = summary
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case bookAuthor = "book_author"
        case bookTitle = "book_title"
        case byline
        case isbn13
        case publicationDt = "publication_dt"
        case summary
        case url
    }

}
