//
// InlineResponse2001Isbns.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2001Isbns: Codable {

    public var isbn10: String?
    public var isbn13: String?

    public init(isbn10: String? = nil, isbn13: String? = nil) {
        self.isbn10 = isbn10
        self.isbn13 = isbn13
    }


}
