//
// InlineResponse2003Results.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2003Results: Codable {

    public var bestsellersDate: String?
    public var lists: [InlineResponse2003ResultsLists]?
    public var publishedDate: String?

    public init(bestsellersDate: String? = nil, lists: [InlineResponse2003ResultsLists]? = nil, publishedDate: String? = nil) {
        self.bestsellersDate = bestsellersDate
        self.lists = lists
        self.publishedDate = publishedDate
    }

    public enum CodingKeys: String, CodingKey { 
        case bestsellersDate = "bestsellers_date"
        case lists
        case publishedDate = "published_date"
    }

}
