//
// InlineResponse2001Reviews.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2001Reviews: Codable {

    public var articleChapterLink: String?
    public var bookReviewLink: String?
    public var firstChapterLink: String?
    public var sundayReviewLink: String?

    public init(articleChapterLink: String? = nil, bookReviewLink: String? = nil, firstChapterLink: String? = nil, sundayReviewLink: String? = nil) {
        self.articleChapterLink = articleChapterLink
        self.bookReviewLink = bookReviewLink
        self.firstChapterLink = firstChapterLink
        self.sundayReviewLink = sundayReviewLink
    }

    public enum CodingKeys: String, CodingKey { 
        case articleChapterLink = "article_chapter_link"
        case bookReviewLink = "book_review_link"
        case firstChapterLink = "first_chapter_link"
        case sundayReviewLink = "sunday_review_link"
    }

}
