//
// InlineResponse2003ResultsBooks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2003ResultsBooks: Codable {

    public var ageGroup: String?
    public var author: String?
    public var contributor: String?
    public var contributorNote: String?
    public var createdDate: String?
    public var _description: String?
    public var price: Int?
    public var primaryIsbn10: String?
    public var primaryIsbn13: String?
    public var publisher: String?
    public var rank: Int?
    public var title: String?
    public var updatedDate: String?

    public init(ageGroup: String? = nil, author: String? = nil, contributor: String? = nil, contributorNote: String? = nil, createdDate: String? = nil, _description: String? = nil, price: Int? = nil, primaryIsbn10: String? = nil, primaryIsbn13: String? = nil, publisher: String? = nil, rank: Int? = nil, title: String? = nil, updatedDate: String? = nil) {
        self.ageGroup = ageGroup
        self.author = author
        self.contributor = contributor
        self.contributorNote = contributorNote
        self.createdDate = createdDate
        self._description = _description
        self.price = price
        self.primaryIsbn10 = primaryIsbn10
        self.primaryIsbn13 = primaryIsbn13
        self.publisher = publisher
        self.rank = rank
        self.title = title
        self.updatedDate = updatedDate
    }

    public enum CodingKeys: String, CodingKey { 
        case ageGroup = "age_group"
        case author
        case contributor
        case contributorNote = "contributor_note"
        case createdDate = "created_date"
        case _description = "description"
        case price
        case primaryIsbn10 = "primary_isbn10"
        case primaryIsbn13 = "primary_isbn13"
        case publisher
        case rank
        case title
        case updatedDate = "updated_date"
    }

}
