//
// InlineResponse2001RanksHistory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2001RanksHistory {

    public var asterisk: Int?
    public var bestsellersDate: String?
    public var dagger: Int?
    public var displayName: String?
    public var listName: String?
    public var primaryIsbn10: String?
    public var primaryIsbn13: String?
    public var publishedDate: String?
    public var rank: Int?
    public var ranksLastWeek: Any?
    public var weeksOnList: Int?

    public init(asterisk: Int? = nil, bestsellersDate: String? = nil, dagger: Int? = nil, displayName: String? = nil, listName: String? = nil, primaryIsbn10: String? = nil, primaryIsbn13: String? = nil, publishedDate: String? = nil, rank: Int? = nil, ranksLastWeek: Any? = nil, weeksOnList: Int? = nil) {
        self.asterisk = asterisk
        self.bestsellersDate = bestsellersDate
        self.dagger = dagger
        self.displayName = displayName
        self.listName = listName
        self.primaryIsbn10 = primaryIsbn10
        self.primaryIsbn13 = primaryIsbn13
        self.publishedDate = publishedDate
        self.rank = rank
        self.ranksLastWeek = ranksLastWeek
        self.weeksOnList = weeksOnList
    }

    public enum CodingKeys: String, CodingKey { 
        case asterisk
        case bestsellersDate = "bestsellers_date"
        case dagger
        case displayName = "display_name"
        case listName = "list_name"
        case primaryIsbn10 = "primary_isbn10"
        case primaryIsbn13 = "primary_isbn13"
        case publishedDate = "published_date"
        case rank
        case ranksLastWeek = "ranks_last_week"
        case weeksOnList = "weeks_on_list"
    }

}
