//
// InlineResponse2004ResultsBooks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2004ResultsBooks: Codable {

    public var ageGroup: String?
    public var amazonProductUrl: String?
    public var articleChapterLink: String?
    public var asterisk: Int?
    public var author: String?
    public var bookImage: String?
    public var bookReviewLink: String?
    public var contributor: String?
    public var contributorNote: String?
    public var dagger: Int?
    public var _description: String?
    public var firstChapterLink: String?
    public var isbns: [InlineResponse2001Isbns]?
    public var price: Int?
    public var primaryIsbn10: String?
    public var primaryIsbn13: String?
    public var publisher: String?
    public var rank: Int?
    public var rankLastWeek: Int?
    public var sundayReviewLink: String?
    public var title: String?
    public var weeksOnList: Int?

    public init(ageGroup: String? = nil, amazonProductUrl: String? = nil, articleChapterLink: String? = nil, asterisk: Int? = nil, author: String? = nil, bookImage: String? = nil, bookReviewLink: String? = nil, contributor: String? = nil, contributorNote: String? = nil, dagger: Int? = nil, _description: String? = nil, firstChapterLink: String? = nil, isbns: [InlineResponse2001Isbns]? = nil, price: Int? = nil, primaryIsbn10: String? = nil, primaryIsbn13: String? = nil, publisher: String? = nil, rank: Int? = nil, rankLastWeek: Int? = nil, sundayReviewLink: String? = nil, title: String? = nil, weeksOnList: Int? = nil) {
        self.ageGroup = ageGroup
        self.amazonProductUrl = amazonProductUrl
        self.articleChapterLink = articleChapterLink
        self.asterisk = asterisk
        self.author = author
        self.bookImage = bookImage
        self.bookReviewLink = bookReviewLink
        self.contributor = contributor
        self.contributorNote = contributorNote
        self.dagger = dagger
        self._description = _description
        self.firstChapterLink = firstChapterLink
        self.isbns = isbns
        self.price = price
        self.primaryIsbn10 = primaryIsbn10
        self.primaryIsbn13 = primaryIsbn13
        self.publisher = publisher
        self.rank = rank
        self.rankLastWeek = rankLastWeek
        self.sundayReviewLink = sundayReviewLink
        self.title = title
        self.weeksOnList = weeksOnList
    }

    public enum CodingKeys: String, CodingKey { 
        case ageGroup = "age_group"
        case amazonProductUrl = "amazon_product_url"
        case articleChapterLink = "article_chapter_link"
        case asterisk
        case author
        case bookImage = "book_image"
        case bookReviewLink = "book_review_link"
        case contributor
        case contributorNote = "contributor_note"
        case dagger
        case _description = "description"
        case firstChapterLink = "first_chapter_link"
        case isbns
        case price
        case primaryIsbn10 = "primary_isbn10"
        case primaryIsbn13 = "primary_isbn13"
        case publisher
        case rank
        case rankLastWeek = "rank_last_week"
        case sundayReviewLink = "sunday_review_link"
        case title
        case weeksOnList = "weeks_on_list"
    }

}
