//
// InlineResponse2004Results.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2004Results : Decodable {

    public var bestsellersDate: String?
    public var books: [InlineResponse2004ResultsBooks]?
    public var corrections: [Any]?
    public var displayName: String?
    public var listName: String?
    public var normalListEndsAt: Int?
    public var publishedDate: String?
    public var updated: String?

    public init(bestsellersDate: String? = nil, books: [InlineResponse2004ResultsBooks]? = nil, corrections: [Any]? = nil, displayName: String? = nil, listName: String? = nil, normalListEndsAt: Int? = nil, publishedDate: String? = nil, updated: String? = nil) {
        self.bestsellersDate = bestsellersDate
        self.books = books
        self.corrections = corrections
        self.displayName = displayName
        self.listName = listName
        self.normalListEndsAt = normalListEndsAt
        self.publishedDate = publishedDate
        self.updated = updated
    }
    
    public init(from decoder: Decoder) throws { }

    public enum CodingKeys: String, CodingKey { 
        case bestsellersDate = "bestsellers_date"
        case books
        case corrections
        case displayName = "display_name"
        case listName = "list_name"
        case normalListEndsAt = "normal_list_ends_at"
        case publishedDate = "published_date"
        case updated
    }

}
